SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RE ON RE.MEMBER_ID = MP.MEMBER_ID
WHERE MP.MEMBER_ID = (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC
FETCH FIRST 1 ROWS ONLY)
ORDER BY REVIEW_DATE, REVIEW_TEXT;
