-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계
-- 년, 월, 성별을 기준으로 오름차순 정렬
-- 성별 정보가 없는 경우 결과에서 제외
-- 동일한 날짜, 회원 ID, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재합니다.
SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR, EXTRACT(MONTH FROM SALES_DATE) MONTH, GENDER, COUNT(DISTINCT OS.USER_ID) USERS 
FROM USER_INFO UI 
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;
