-- 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력
-- 결과는 저자 ID를 오름차순으로,카테고리를 내림차순 정렬

WITH A AS (
  SELECT BOOK_ID, SALES 
  FROM BOOK_SALES
  WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
)
,
B AS (
SELECT BK.AUTHOR_ID, BK.CATEGORY, SUM(BK.PRICE*A.SALES) AS TOTAL_SALES
FROM BOOK BK, A
WHERE BK.BOOK_ID = A.BOOK_ID
GROUP BY BK.AUTHOR_ID, BK.CATEGORY)

SELECT AU.AUTHOR_ID AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM B, AUTHOR AU
WHERE B.AUTHOR_ID = AU.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;


-- chatGPT가 수정한 내 쿼리
SELECT AU.AUTHOR_ID AUTHOR_ID, AU.AUTHOR_NAME, BK.CATEGORY, SUM(BK.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK BK
JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR AU ON BK.AUTHOR_ID = AU.AUTHOR_ID
WHERE TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY AU.AUTHOR_ID, AU.AUTHOR_NAME, BK.CATEGORY
ORDER BY AU.AUTHOR_ID, BK.CATEGORY DESC;
