-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회
WITH A AS (
SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR
),
B AS (
SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF 
GROUP BY FLAVOR
)

SELECT FLAVOR 
FROM (
SELECT A.FLAVOR FLAVOR, (A.TOTAL_ORDER+B.TOTAL_ORDER) PRICE FROM A
JOIN B ON A.FLAVOR = B.FLAVOR
ORDER BY PRICE DESC
)
WHERE ROWNUM <= 3;

-- FETCH FIRST 문을 사용하여 최종 결과에서 상위 3개의 레코드만 선택 
-- ROWNUM 보다 좋은 성능
SELECT HAL.FLAVOR
FROM FIRST_HALF HAL 
JOIN JULY JU ON HAL.FLAVOR = JU.FLAVOR
GROUP BY HAL.FLAVOR
ORDER BY SUM(HAL.TOTAL_ORDER)+SUM(JU.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY;

