-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
-- 음식 종류를 기준으로 내림차순

WITH A AS (
SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES FROM REST_INFO
GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, R.REST_ID, R.REST_NAME, A.FAVORITES
FROM A, REST_INFO R
WHERE A.FOOD_TYPE = R.FOOD_TYPE AND A.FAVORITES = R.FAVORITES
ORDER BY FOOD_TYPE DESC;


-- chatGPT가 수정한 코드
SELECT A.FOOD_TYPE, R.REST_ID, R.REST_NAME, A.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) A
JOIN REST_INFO R
ON A.FOOD_TYPE = R.FOOD_TYPE AND A.FAVORITES = R.FAVORITES
ORDER BY A.FOOD_TYPE DESC;
