-- 코드를 입력하세요
WITH A AS (
SELECT BOOK_ID, CATEGORY FROM BOOK
)

SELECT CATEGORY, SUM(SALES) AS SALES
FROM BOOK_SALES BS, A
WHERE BS.BOOK_ID = A.BOOK_ID 
AND
TO_CHAR(SALES_DATE,'YYYY-MM') LIKE '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY;
