-- 코드를 입력하세요
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT BO.TITLE, BO.BOARD_ID, RE.REPLY_ID, RE.WRITER_ID, RE.CONTENTS, TO_CHAR(RE.CREATED_DATE,'YYYY-MM-DD')
FROM USED_GOODS_BOARD BO, USED_GOODS_REPLY RE 
WHERE BO.BOARD_ID = RE.BOARD_ID
AND EXTRACT(MONTH FROM BO.CREATED_DATE) = 10
ORDER BY RE.CREATED_DATE, TITLE;
