SELECT CAR_ID, ROUND(AVG(end_date - start_date+1),1) AVERAGE_DURATION from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
HAVING AVG(end_date - start_date)  >= 6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
