-- 코드를 입력하세요
SELECT 
HISTORY_ID
, CAR_ID
, TO_CHAR(TO_DATE(START_DATE),'YYYY-MM-DD') START_DATE
, TO_CHAR(TO_DATE(END_DATE),'YYYY-MM-DD') END_DATE
, CASE 
WHEN (END_DATE-START_DATE+1 >=30) THEN '장기 대여'
ELSE '단기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE EXTRACT(MONTH FROM START_DATE) = 9
ORDER BY HISTORY_ID DESC;
