WITH CON AS(
SELECT WRITER_ID, COUNT(WRITER_ID) CNT
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
)

SELECT 
US.USER_ID
, US.NICKNAME
, CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2 AS 전체주소
, SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8) 전화번호 
FROM USED_GOODS_USER US, CON CO
WHERE US.USER_ID = CO.WRITER_ID
ORDER BY 1 DESC;
