-- 가장 뷰가 많은 게시물 찾기
-- SELECT * FROM (
-- SELECT BOARD_ID
-- FROM USED_GOODS_BOARD
-- ORDER BY VIEWS DESC
-- )
-- WHERE ROWNUM = 1;

-- 가장 뷰가 많의 게시물의 경로
SELECT '/home/grep/src/'||''||BO.BOARD_ID||'/'||FI.FILE_ID||''||FI.FILE_NAME||''||FI.FILE_EXT AS PATH_FILE
FROM (SELECT BOARD_ID FROM (
SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
)
WHERE ROWNUM = 1) BO, USED_GOODS_FILE FI
WHERE BO.BOARD_ID = FI.BOARD_ID
ORDER BY FILE_ID DESC;
