SELECT APNT_NO, PT_NAME, PT.PT_NO, DOC.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AP, DOCTOR DOC, PATIENT PT
WHERE AP.PT_NO = PT.PT_NO 
AND AP.MDDR_ID = DOC.DR_ID 
AND AP.MCDP_CD = 'CS'
AND AP.APNT_CNCL_YN ='N'
AND TO_CHAR(APNT_YMD,'YYYY-MM-DD') = '2022-04-13'
ORDER BY 6 ;
